version: "3"
services:
  mumble:
    image: mumblevoip/mumble-server:latest
    container_name: mumble_server
    ports:
      - 64738:64738/tcp
      - 64738:64738/udp
    environment:
      - MUMBLE_SERVERNAME=Mumble Server
      - MUMBLE_MAXUSERS=50
      - MUMBLE_CONFIG_SERVERPASSWORD=${MUMBLE_PASSWORD}
      - MUMBLE_BANDWIDTH=72000
      - MUMBLE_SUPERUSER_PASSWORD=${MUMBLE_SUPERUSER_PASSWORD}
    volumes:
      - ./mumble-data:/data
    restart: always